# Configuration for Cloudflare Pages with KV bindings
name = "calendar"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"
main = "src/worker.ts"

[assets]
directory = "./dist"

[[kv_namespaces]]
binding = "DERM_STORE"
# Replace with your actual Cloudflare KV Namespace ID
id = "65d9d98d3ad3488991aa4b67d94130d8"
